### ISSUE TITLE
Watcher sometimes dies

### ISSUE THREAD

**Issue by mullwaden** [ivanhofer/typesafe-i18n#314]
### Version

5.4.2

### Describe the bug

Since upgrading from version 2 to 5 i have had the watcher crash on me several times per day with the following error:

```
[start:i18n  ] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
[start:i18n  ]     at new NodeError (node:internal/errors:371:5)
[start:i18n  ]     at validateString (node:internal/validators:119:11)
[start:i18n  ]     at join (node:path:429:7)
[start:i18n  ]     at Number.onChange (file:///C:/dev/inex/node_modules/typesafe-i18n/cli/typesafe-i18n.mjs:14861:15)
[start:i18n  ]     at FSWatcher.emit (node:events:390:28)
[start:i18n  ]     at FSWatcher.emit (node:domain:475:12)
[start:i18n  ]     at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:212:12) {
[start:i18n  ]   code: 'ERR_INVALID_ARG_TYPE'
[start:i18n  ] }
```

Not really sure what is going on, restarting the watcher always works.

### Reproduction

Reproduction is tricky, it seems to coincide with when i make changes to our frontend (same repository, different folder)

**Comment by ivanhofer** [comment]
Hi @mullwaden,
version `5.4.3` is the latest released version. Could you please check if the issue is still present there?

The stacktrace points me to this line:
![image](https://user-images.githubusercontent.com/21335119/169388048-8d242ef5-1539-4bb5-8354-0ee9220d90d2.png)

Can you please confirm?

Since it happened a few times, yould you please manually add some `console.log` statements to the line before to see what exact entry is `null`?

Other questions:
1. do you use namespaces?
2. What operating System are you working with?
3. What Node.js version are you running?

It would be great if you can help me identify the bug since you are the first person who encountered the isssue.

You could also try going back to version `5.3.6`. I have replaced the watcher package in version `5.4.0` and I think you trigger some edge-cases there.

**Comment by mullwaden** [comment]
Testing in 5.4.2
- Can confirm it is the line above, the filename is null. 
- windows 10
- Node 16

My guess would be that the filewatcher on windows somehow behaves differently than on mac/linux. 

Not using any fancy stuff, my base setup looks like this:

```
import { i18n as initI18n } from "typesafe-i18n";

import type {
  Translation,
  TranslationFunctions,
  Formatters,
  Locales,
} from "./i18n-types";
import { initFormatters } from "./formatters";
import en from "./en";

export const getTranslationForLocale = () => en as Translation;

const i18n = initI18n<Locales, Translation, TranslationFunctions, Formatters>(
  { en: getTranslationForLocale() },
  { en: initFormatters("en") }
);

export default i18n.en;
```


will test 5.4.3 now

**Comment by ivanhofer** [comment]
@mullwaden thanks for the information.
Yeah, probably some windows specific issue. I'll take a deeper look at this next week.
In the meantime, version `5.3.6` should work for you.

**Comment by ivanhofer** [comment]
@mullwaden I could not reproduce the issue. I have reverted the change to use the previous library. Version `5.5.0` should work for you.

The reason why I switched to `watchlist` was a bundling issue with `rollup`. But it seems this is no longer the case. Probably the recent switch to `esbuild` fixed it.
