### ISSUE TITLE
Node.js error on localization key called `length`

### ISSUE THREAD

**Issue by maxxxxxdlp** [ivanhofer/typesafe-i18n#543]
### Version

5.17.1

### Describe the bug

Calling `i18nObject` fails in Node.js if you have a localization string with key `length`

### Reproduction

Run this in Node.js:

```js
const {i18nObject} = require('typesafe-i18n');
i18nObject('en-us', {length: 'bug'});
```

### Logs

```sh
Uncaught TypeError: Cannot assign to read only property 'length' of function '() => '''
    at Function.assign (<anonymous>)
    at wrap (/Users/maxpatiiuk/site/python/specify7/specifyweb/frontend/js_src/node_modules/typesafe-i18n/runtime/cjs/runtime/src/util.object.cjs:23:14)
    at createProxy (/Users/maxpatiiuk/site/python/specify7/specifyweb/frontend/js_src/node_modules/typesafe-i18n/runtime/cjs/runtime/src/util.object.cjs:27:66)
    at i18nObject (/Users/maxpatiiuk/site/python/specify7/specifyweb/frontend/js_src/node_modules/typesafe-i18n/runtime/cjs/runtime/src/util.object.cjs:13:12)
```

### Config

```JSON
No config file
```

### Additional information

Happens when run in Node.js v19.2.0
Does not happen when run in Google Chrome Beta 109

**Comment by ivanhofer** [comment]
Hi @maxxxxxdlp,

'caller', 'callee', 'arguments and 'length' are reserved keywords that can't be used as keys.

The code that produces this error looks like this:
```ts
const fn = () => ''
const obj = Object.assign(fn, { length: 'bug' })
```
In the end `obj` is a function that also has the properties attached that you pass as the second argument.

In order to make `length` valid, we would need to find a way to merge a function with an object, but without the `length` attribute of the function itself. I'm currently not aware of such a way.

The only thing I can currently do is to add a hint to the docs.

**Comment by maxxxxxdlp** [comment]
Thanks!
I want to mention that this is not a big issue for us and that renaming the key solved the problem.
I opened this issue just in case you were not already aware of this limitation.

Out of curiosity, could you explain briefly why `obj` needs to be a function rather than an object? Is this a limitation of a Proxy? I'm sorry if you already mentioned this in the docs

**Comment by nkoehring** [comment]
I guess it is because one needs to be able to use template string parameters, for example when you have the translation string `apples: '{n} apple{{s}}'`, you'd use `LL.apples(23)` or `LL.apples({n: 42})` .

**Comment by ivanhofer** [comment]
I have added a note to the docs: https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/runtime#dictionary
