### ISSUE TITLE
Can typesafe can use with nextjs?

### ISSUE THREAD

**Issue by IRediTOTO** [ivanhofer/typesafe-i18n#72]
Hi, can your pack use with nexti18 package ? THank you

**Comment by ivanhofer** [comment]
Hi @IRediTOTO,
yes, `typesafe-i18n` should work with Next.js.
You will need to set the [`adapter`-option](https://github.com/ivanhofer/typesafe-i18n#adapter) to `'react'`.

**Comment by IRediTOTO** [comment]
I am starting using this, but the docs... Can you write it more clear a little for newbie like me? What files should I create, what code should I put in. Want a easy started.

**Comment by ivanhofer** [comment]
You should take a look at the react-example: https://github.com/ivanhofer/typesafe-i18n/tree/main/examples/react
You should find everything there

**Comment by ivanhofer** [comment]
@IRediTOTO did it work with Next.js?

**Comment by IRediTOTO** [comment]
> @IRediTOTO did it work with Next.js?

Yes, NextJS.

**Comment by IRediTOTO** [comment]
I am using next-translate pack. But your pack is best idea i think, never missed a text. I just worry about performance, run much js on client can make UX slow (same as css in js - I used css file for now)

**Comment by ivanhofer** [comment]
I don't think `typesafe-i18n` causes performance problems. It is well optimized and adds only a small amount of JavaScript to your bundle. If you have concerns about a slow UX, then maybe React is not the best choice, since the diffing of the virtual DOM is slow on heavy interactive sites. But I don't think you will experience any performance issues in a small- to medium-sized project 😉
